spring:
  #配置数据
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    name: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #项目运行时运行sql
    schema:
      - classpath:sql/account.sql
      - classpath:sql/employee.sql
    initialization-mode: always
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    #修改springboot默认的静态文件路径
    static-path-pattern: /**
  #禁用thymeleaf模板引擎的缓存
  thymeleaf:
    cache: false